### ISSUE TITLE
运行`npm run dev-server`没反应

### ISSUE THREAD

**Issue by mcattx** [icepy/kodo#1]
我把项目 `clone` 到本地，然后按照`README.md`运行`npm install`安装完依赖，然后全局安装`nodemon`。
跑`npm run dev-server`命令后没有反应，看一下控制台，发现`nodemon`运行没报错。

![1](https://cloud.githubusercontent.com/assets/3294102/15383485/f2cc88c4-1dc5-11e6-86d0-8b82ea6225fc.png)

然后我手动在浏览器输入地址：`http://localhost:3001/`

![2](https://cloud.githubusercontent.com/assets/3294102/15383513/3a2b86f2-1dc6-11e6-9e05-2f86d2a8ad61.png)

这时候我看一下日志，发现`koa`服务器其实已经启动成功，但是跳到`404`。

![3](https://cloud.githubusercontent.com/assets/3294102/15383527/4d823034-1dc6-11e6-9262-aaffc605b6a5.png)

**Comment by icepy** [comment]
@titancat 你需要输入`http://127.0.0.1:3001/examples/dialog.html`，demo都放在examples目录中。

**Comment by mcattx** [comment]
@icepy 可以了。谢谢。
