### ISSUE TITLE
safari浏览器 dialog有问题

### ISSUE THREAD

**Issue by yizao** [icepy/kodo#4]

**Comment by icepy** [comment]
@sosocter [issues问题风格建议](https://github.com/mulgore/kodo/wiki/issues%E9%97%AE%E9%A2%98%E9%A3%8E%E6%A0%BC%E5%BB%BA%E8%AE%AE)，还请你给予必要的信息。

**Comment by yizao** [comment]
![2 pic_hd](https://cloud.githubusercontent.com/assets/3366673/16036500/d98aca9a-324e-11e6-8ec0-d76179a92af3.jpg)

dialog在遮罩层后面

**Comment by icepy** [comment]
@sosocter 浏览器版本？

**Comment by yizao** [comment]
@icepy 
![image](https://cloud.githubusercontent.com/assets/3366673/16177797/599b3f80-3669-11e6-88b1-a731f9c56b39.png)

**Comment by icepy** [comment]
@0928 这个问题修复了。
